/* ShiftPulse: local-first shift journal */
const DB_NAME="ShiftPulseDB", DB_VERSION=1, STORE="shifts", SETTINGS_KEY="shiftpulse_settings";
const state={view:"home", editId:null, historyFilter:"month", statsMode:"month", calendarDate:new Date(), shifts:[], settings:{goal:176,weekStart:1,timeFormat:"24"}};
const $=s=>document.querySelector(s);
const fmt2=n=>String(n).padStart(2,"0");
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random().toString(16).slice(2);
const dateISO=d=>{const x=new Date(d);return `${x.getFullYear()}-${fmt2(x.getMonth()+1)}-${fmt2(x.getDate())}`};
const parseLocal=(date,time)=>{const [h,m]=time.split(":").map(Number);const d=new Date(`${date}T00:00:00`);d.setHours(h,m,0,0);return d};
const minsToHM=m=>{m=Math.max(0,Math.round(m));return `${Math.floor(m/60)}ч ${fmt2(m%60)}м`};
const minsToClock=m=>`${fmt2(Math.floor(m/60))}:${fmt2(m%60)}`;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const ruDate=d=>new Intl.DateTimeFormat("ru-RU",{day:"numeric",month:"long"}).format(d);
const ruFull=d=>new Intl.DateTimeFormat("ru-RU",{weekday:"long",day:"numeric",month:"long",year:"numeric"}).format(d);
const monthName=d=>new Intl.DateTimeFormat("ru-RU",{month:"long",year:"numeric"}).format(d);
const sameMonth=(a,b)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth();
const completed=()=>state.shifts.filter(s=>s.status==="completed");
function durationFor(date,start,end,br){let a=parseLocal(date,start),b=parseLocal(date,end);if(b<=a)b.setDate(b.getDate()+1);return Math.max(0,Math.round((b-a)/60000)-Math.max(0,Number(br)||0))}
function calcFormDuration(){const f=$("#shiftForm");if(!f)return;const date=f.date.value,start=f.start.value,end=f.end.value,br=f.break.value||"0";if(date&&start&&end){let m=durationFor(date,start,end,br);$("#durationPreview").innerHTML=`Итоговое рабочее время<br><b>${minsToHM(m)}</b>`}}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const st=db.createObjectStore(STORE,{keyPath:"id"});st.createIndex("date","date")}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function dbAll(){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function dbPut(x){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE,"readwrite").objectStore(STORE).put(x);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function dbDelete(id){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE,"readwrite").objectStore(STORE).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
async function dbClear(){const db=await openDB();return new Promise((res,rej)=>{const r=db.transaction(STORE,"readwrite").objectStore(STORE).clear();r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function loadSettings(){try{state.settings={...state.settings,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}")}}catch{}}
function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(state.settings))}
function activeShift(){return state.shifts.find(s=>s.status==="active")}
function monthStats(d=new Date()){const xs=completed().filter(s=>sameMonth(new Date(s.date),d));const total=xs.reduce((a,s)=>a+s.durationMinutes,0);return{xs,total,avg:xs.length?Math.round(total/xs.length):0}}
function filteredHistory(){const now=new Date();let start=new Date(now.getFullYear(),now.getMonth(),now.getDate()),end=new Date(now);if(state.historyFilter==="today"){end.setHours(23,59,59)}else if(state.historyFilter==="week"){const day=(now.getDay()+6)%7;start.setDate(now.getDate()-day);end=new Date(start);end.setDate(start.getDate()+6);end.setHours(23,59,59)}else if(state.historyFilter==="month"){start=new Date(now.getFullYear(),now.getMonth(),1);end=new Date(now.getFullYear(),now.getMonth()+1,0,23,59,59)}else if(state.historyFilter==="prev"){start=new Date(now.getFullYear(),now.getMonth()-1,1);end=new Date(now.getFullYear(),now.getMonth(),0,23,59,59)}else if(state.historyFilter==="year"){start=new Date(now.getFullYear(),0,1);end=new Date(now.getFullYear(),11,31,23,59,59)}else{start=new Date(0);end=new Date(8640000000000000)}return completed().filter(s=>{const d=new Date(s.date);return d>=start&&d<=end}).sort((a,b)=>new Date(b.date)-new Date(a.date)||b.createdAt-a.createdAt)}
function greeting(){const h=new Date().getHours();return h<5?"Доброй ночи":h<12?"Доброе утро":h<18?"Добрый день":"Добрый вечер"}
const navItems=[["home","🏠","Главная"],["add","＋","Новая смена"],["stats","◒","Статистика"],["history","▦","История"]];
function renderNav(){const html=navItems.map(([id,icon,label])=>`<button class="nav-item ${state.view===id?"active":""}" data-nav="${id}"><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join("");$("#sideNav").innerHTML=html;$("#bottomNav").innerHTML=html}
function render(){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$("#view-"+state.view).classList.add("active");renderNav();if(state.view==="home")renderHome();if(state.view==="add")renderAdd();if(state.view==="stats")renderStats();if(state.view==="history")renderHistory();if(state.view==="settings")renderSettings();$("#pageTitle").textContent=state.view==="home"?greeting():({add:"Новая смена",stats:"Статистика",history:"История смен",settings:"Настройки"}[state.view]||"ShiftPulse");$("#todayLabel").textContent=new Intl.DateTimeFormat("en-US",{weekday:"long",month:"short",day:"numeric"}).format(new Date()).toUpperCase()}
function renderHome(){const now=new Date(), a=activeShift(), ms=monthStats(now), goal=Number(state.settings.goal)||0, pct=goal?Math.min(100,ms.total/goal*100):0,last=completed().sort((x,y)=>new Date(y.date)-new Date(x.date)||y.createdAt-x.createdAt)[0];$("#view-home").innerHTML=`<div class="home-grid grid"><div class="status-card">${a?`<div class="status-head"><span class="status-pill">🟠 НА СМЕНЕ</span><span class="sub">LIVE</span></div><h2>Рабочий режим</h2><div class="sub">Начало: ${esc(a.startTime)} · ${ruDate(new Date(a.date))}</div><div class="timer" id="liveTimer">00:00:00</div><button class="btn" data-action="finish">Завершить смену</button>`:`<div class="status-head"><span class="status-pill done">● ГОТОВ</span><span class="sub">CURRENT STATUS</span></div><h2>Не на смене</h2><div class="sub">Твой рабочий журнал готов к следующей записи.</div><div class="timer">— —</div><button class="btn" data-action="start">Начать смену</button>`}</div><div class="panel"><div class="section-head" style="margin-top:0"><h3>THIS MONTH</h3><span>${monthName(now)}</span></div><div class="big-stat">${ms.xs.length} смен</div><div class="sub">${minsToHM(ms.total)} рабочего времени</div><div class="progress"><i style="width:${pct}%"></i></div><div class="progress-row"><span>${minsToHM(ms.total)} / ${goal?minsToHM(goal*60):"цель не задана"}</span><b>${goal?pct.toFixed(1)+"%":"—"}</b></div></div></div><div class="stats-grid"><div class="metric"><span class="label">Смены в этом месяце</span><span class="value">${ms.xs.length}</span></div><div class="metric"><span class="label">Часов в этом месяце</span><span class="value">${minsToHM(ms.total)}</span></div><div class="metric"><span class="label">Средняя смена</span><span class="value">${minsToHM(ms.avg)}</span></div><div class="metric"><span class="label">Всего смен</span><span class="value">${completed().length}</span></div></div><div class="dashboard-two"><div><div class="section-head"><h3>Последняя смена</h3><span>${last?"TODAY / LATEST":"EMPTY"}</span></div>${last?shiftCard(last):emptyState("◷","История пока пуста","Добавь первую смену и начни собирать рабочую статистику.","add")}</div><div><div class="section-head"><h3>Месячная цель</h3><span>TARGET</span></div><div class="month-card"><div class="month-title"><strong>${new Intl.DateTimeFormat("ru-RU",{month:"long"}).format(now).toUpperCase()} ${now.getFullYear()}</strong><span>${goal}ч цель</span></div><div class="big-stat">${pct.toFixed(1)}%</div><div class="progress"><i style="width:${pct}%"></i></div><div class="progress-row"><span>${goal&&ms.total>=goal*60?"Цель месяца выполнена 🎉":"Осталось "+minsToHM(Math.max(0,goal*60-ms.total))}</span><span>${minsToHM(ms.total)}</span></div></div></div></div><div class="section-head"><h3>Календарь</h3><span>РАБОЧАЯ АКТИВНОСТЬ</span></div>${calendarHTML(now)}</div>`;if(a)updateTimer()}
function updateTimer(){const a=activeShift(),el=$("#liveTimer");if(!a||!el)return;const start=parseLocal(a.date,a.startTime);const tick=()=>{if(!$("#liveTimer"))return;const sec=Math.max(0,Math.floor((Date.now()-start.getTime())/1000));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;$("#liveTimer").textContent=`${fmt2(h)}:${fmt2(m)}:${fmt2(s)}`};tick();clearInterval(window.__timer);window.__timer=setInterval(tick,1000)}
function emptyState(icon,title,text,nav="add"){return `<div class="empty"><div class="empty-icon">${icon}</div><strong>${title}</strong><div>${text}</div><br><button class="btn" data-nav="${nav}">+ Добавить смену</button></div>`}
function shiftCard(s){const d=new Date(s.date);return `<div class="shift-card"><div class="shift-top"><div class="shift-date">${ruDate(d)}<small>${new Intl.DateTimeFormat("ru-RU",{weekday:"long"}).format(d)}</small></div><div class="actions"><button class="mini-btn" data-edit="${s.id}">Редактировать</button><button class="mini-btn" data-delete="${s.id}">Удалить</button></div></div><div class="shift-times"><strong>${esc(s.startTime)}</strong><span class="shift-arrow">→</span><strong>${esc(s.endTime)}</strong></div><div class="shift-bottom"><small>Рабочее время${s.breakMinutes?` · перерыв ${minsToHM(s.breakMinutes)}`:""}</small><span class="duration">${minsToHM(s.durationMinutes)}</span></div>${s.comment?`<div class="notice" style="margin-top:10px">“${esc(s.comment)}”</div>`:""}</div>`}
function renderAdd(){const edit=state.editId?state.shifts.find(s=>s.id===state.editId):null, d=edit?edit.date:dateISO(new Date()), st=edit?edit.startTime:fmt2(new Date().getHours())+":"+fmt2(new Date().getMinutes()), en=edit?edit.endTime:"18:00", br=edit?minsToClock(edit.breakMinutes):"00:00";$("#view-add").innerHTML=`<div class="panel"><div class="section-head" style="margin-top:0"><h3>${edit?"Редактировать смену":"Новая смена"}</h3><span>${edit?"EDIT MODE":"MANUAL ENTRY"}</span></div><form class="form" id="shiftForm"><div class="field"><label>Дата</label><input name="date" type="date" value="${d}" required></div><div class="two-col"><div class="field"><label>Начало</label><input name="start" type="time" value="${st}" required></div><div class="field"><label>Окончание</label><input name="end" type="time" value="${en}" required></div></div><div class="field"><label>Перерыв</label><input name="break" type="time" value="${br}" min="00:00" required></div><div class="field"><label>Комментарий · необязательно</label><textarea name="comment" placeholder="Например: дневная смена">${esc(edit?.comment||"")}</textarea></div><div class="preview" id="durationPreview">Итоговое рабочее время<br><b>—</b></div><button class="btn" type="submit">${edit?"Сохранить изменения":"Сохранить смену"}</button>${edit?`<button class="btn secondary" type="button" data-nav="history">Отмена</button>`:""}</form></div>`;$("#shiftForm").addEventListener("input",calcFormDuration);$("#shiftForm").addEventListener("submit",saveShiftForm);calcFormDuration()}
async function saveShiftForm(e){e.preventDefault();const f=e.currentTarget, m=durationFor(f.date.value,f.start.value,f.end.value,f.break.value);if(!f.date.value||!f.start.value||!f.end.value)return toast("Заполни дату и время");if(Number(f.break.value.split(":")[0])>23)return toast("Некорректный перерыв");const existing=state.editId?state.shifts.find(s=>s.id===state.editId):null;const x={id:existing?.id||uid(),date:f.date.value,startTime:f.start.value,endTime:f.end.value,breakMinutes:(Number(f.break.value.split(":")[0])*60+Number(f.break.value.split(":")[1])),durationMinutes:m,comment:f.comment.value.trim(),status:"completed",createdAt:existing?.createdAt||Date.now()};await dbPut(x);state.shifts=await dbAll();state.editId=null;state.view="history";toast("Смена сохранена");render()}
async function startShift(){if(activeShift())return;const now=new Date(),x={id:uid(),date:dateISO(now),startTime:fmt2(now.getHours())+":"+fmt2(now.getMinutes()),endTime:null,breakMinutes:0,durationMinutes:0,comment:"",status:"active",createdAt:Date.now()};await dbPut(x);state.shifts=await dbAll();toast("Смена началась");render()}
async function finishShift(){const a=activeShift();if(!a)return;const now=new Date(),start=parseLocal(a.date,a.startTime);let mins=Math.max(0,Math.round((now-start)/60000));a.endTime=fmt2(now.getHours())+":"+fmt2(now.getMinutes());a.durationMinutes=mins;a.status="completed";await dbPut(a);state.shifts=await dbAll();toast(`Смена завершена · ${minsToHM(mins)}`);render()}
function renderHistory(){const filters=[["today","Сегодня"],["week","Эта неделя"],["month","Этот месяц"],["prev","Прошлый месяц"],["year","Этот год"],["all","Все время"]],xs=filteredHistory();$("#view-history").innerHTML=`<div class="filter-row">${filters.map(([id,l])=>`<button class="chip ${state.historyFilter===id?"active":""}" data-filter="${id}">${l}</button>`).join("")}</div><div class="section-head"><h3>${xs.length} ${xs.length===1?"смена":"смен"}</h3><span>НОВЫЕ СВЕРХУ</span></div><div class="shift-list">${xs.length?xs.map(shiftCard).join(""):emptyState("◷","История пуста","Для выбранного периода смен не найдено.","add")}</div>`}
function statsRange(){const now=new Date();if(state.statsMode==="week"){const day=(now.getDay()+6)%7,s=new Date(now);s.setDate(now.getDate()-day);s.setHours(0,0,0,0);const e=new Date(s);e.setDate(s.getDate()+7);return[s,e]}if(state.statsMode==="year")return[new Date(now.getFullYear(),0,1),new Date(now.getFullYear()+1,0,1)];return[new Date(now.getFullYear(),now.getMonth(),1),new Date(now.getFullYear(),now.getMonth()+1,1)]}
function renderStats(){const [s,e]=statsRange(),xs=completed().filter(x=>{const d=new Date(x.date);return d>=s&&d<e}),total=xs.reduce((a,x)=>a+x.durationMinutes,0),avg=xs.length?Math.round(total/xs.length):0,long=Math.max(0,...xs.map(x=>x.durationMinutes)),short=xs.length?Math.min(...xs.map(x=>x.durationMinutes)):0;$("#view-stats").innerHTML=`<div class="segmented">${["week","month","year"].map(x=>`<button class="${state.statsMode===x?"active":""}" data-stats="${x}">${x==="week"?"Неделя":x==="month"?"Месяц":"Год"}</button>`).join("")}</div><div class="stats-grid"><div class="metric"><span class="label">Смен</span><span class="value">${xs.length}</span></div><div class="metric"><span class="label">Рабочих часов</span><span class="value">${minsToHM(total)}</span></div><div class="metric"><span class="label">Средняя смена</span><span class="value">${minsToHM(avg)}</span></div><div class="metric"><span class="label">Самая длинная</span><span class="value">${minsToHM(long)}</span></div></div><div class="dashboard-two"><div class="panel"><div class="section-head" style="margin-top:0"><h3>Рабочие часы</h3><span>${state.statsMode.toUpperCase()}</span></div><div class="chart-wrap"><canvas id="hoursChart" class="chart"></canvas></div></div><div class="panel"><div class="section-head" style="margin-top:0"><h3>Календарь</h3><span>АКТИВНОСТЬ</span></div>${calendarHTML(new Date())}</div></div><div class="section-head"><h3>Дополнительные показатели</h3><span>INSIGHTS</span></div><div class="stats-grid"><div class="metric"><span class="label">Самая короткая</span><span class="value">${minsToHM(short)}</span></div><div class="metric"><span class="label">Среднее часов / нед.</span><span class="value">${minsToHM(Math.round(total/(state.statsMode==="year"?52:state.statsMode==="month"?4.35:1)))}</span></div><div class="metric"><span class="label">Всего рабочее время</span><span class="value">${minsToHM(completed().reduce((a,x)=>a+x.durationMinutes,0))}</span></div><div class="metric"><span class="label">Смен подряд</span><span class="value">${streak()} дней</span></div></div><div class="section-head"><h3>По месяцам</h3><span>HISTORY</span></div><div class="tableish">${monthlyRows()}</div>`;drawChart(xs)}
function drawChart(xs){const c=$("#hoursChart");if(!c)return;const ctx=c.getContext("2d"),dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);const by={};xs.forEach(x=>by[x.date]=(by[x.date]||0)+x.durationMinutes/60);let keys=Object.keys(by).sort(),vals=keys.map(k=>by[k]),max=Math.max(1,...vals);if(state.statsMode==="year"){const mo={};xs.forEach(x=>{const k=x.date.slice(0,7);mo[k]=(mo[k]||0)+x.durationMinutes/60});keys=Object.keys(mo).sort();vals=keys.map(k=>mo[k]);max=Math.max(1,...vals)}ctx.clearRect(0,0,w,h);ctx.font="10px Inter";ctx.fillStyle="#8D95A1";const left=32,bottom=28,top=12,gw=w-left-8,gh=h-top-bottom;for(let i=0;i<4;i++){const y=top+gh*i/3;ctx.strokeStyle="rgba(255,255,255,.07)";ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(w-6,y);ctx.stroke();ctx.fillText(`${Math.round(max*(1-i/3))}h`,2,y+3)}const bw=Math.max(4,Math.min(28,gw/Math.max(1,keys.length)*.55)),gap=gw/Math.max(1,keys.length);vals.forEach((v,i)=>{const bh=gh*v/max,x=left+i*gap+(gap-bw)/2,y=top+gh-bh;const g=ctx.createLinearGradient(0,y,0,top+gh);g.addColorStop(0,"#8B6CFF");g.addColorStop(1,"#4E7DFF");ctx.fillStyle=g;ctx.beginPath();ctx.roundRect(x,y,bw,bh,6);ctx.fill();ctx.fillStyle="#8D95A1";const label=state.statsMode==="year"?keys[i].slice(5):keys[i].slice(8);ctx.fillText(label,x-2, h-8)})}
function monthlyRows(){const rows=[];const now=new Date();for(let i=0;i<6;i++){const d=new Date(now.getFullYear(),now.getMonth()-i,1),m=monthStats(d);rows.push(`<div class="month-row"><strong>${new Intl.DateTimeFormat("ru-RU",{month:"long",year:"numeric"}).format(d)}</strong><span>${m.xs.length} смен · ${minsToHM(m.total)}</span></div>`)}return rows.join("")}
function streak(){const days=[...new Set(completed().map(s=>s.date))].sort().reverse();if(!days.length)return 0;let n=1;for(let i=1;i<days.length;i++){const a=new Date(days[i-1]),b=new Date(days[i]);if((a-b)/86400000===1)n++;else break}return n}
function calendarHTML(base){const y=base.getFullYear(),m=base.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,days=new Date(y,m+1,0).getDate(),today=dateISO(new Date()),worked=new Set(completed().filter(s=>{const d=new Date(s.date);return d.getFullYear()===y&&d.getMonth()===m}).map(s=>s.date));let out=`<div class="calendar-nav"><button class="icon-mini" data-cal="-1">‹</button><strong>${monthName(base)}</strong><button class="icon-mini" data-cal="1">›</button></div><div class="calendar">`;["Пн","Вт","Ср","Чт","Пт","Сб","Вс"].forEach(x=>out+=`<div class="cal-head">${x}</div>`);for(let i=0;i<start;i++)out+=`<div class="cal-day muted"></div>`;for(let day=1;day<=days;day++){const iso=`${y}-${fmt2(m+1)}-${fmt2(day)}`;out+=`<div class="cal-day ${worked.has(iso)?"work ":""}${iso===today?"today":""}" title="${worked.has(iso)?"Была смена":"Смены нет"}"><button data-calday="${iso}">${day}</button></div>`}return out+"</div>"}
function renderSettings(){$("#view-settings").innerHTML=`<div class="settings-list"><div class="setting-card"><div class="copy"><strong>Цель часов в месяц</strong><span>Используется для прогресса на главной</span></div><input class="setting-control" id="goalInput" type="number" min="0" step="1" value="${state.settings.goal}"></div><div class="setting-card"><div class="copy"><strong>Первый день недели</strong><span>Вид календаря</span></div><select class="setting-control" id="weekStart"><option value="1" ${state.settings.weekStart===1?"selected":""}>Понедельник</option><option value="0" ${state.settings.weekStart===0?"selected":""}>Воскресенье</option></select></div><div class="setting-card"><div class="copy"><strong>Формат времени</strong><span>Для будущих локализованных представлений</span></div><select class="setting-control" id="timeFormat"><option value="24" selected>24 часа</option><option value="12" disabled>12 часов</option></select></div><div class="setting-card"><div class="copy"><strong>Тема</strong><span>ShiftPulse сейчас оптимизирован под dark</span></div><select class="setting-control" disabled><option>Dark</option></select></div><div class="setting-card"><div class="copy"><strong>Экспорт данных</strong><span>Резервная копия или CSV</span></div><div class="actions"><button class="mini-btn" data-export="json">JSON</button><button class="mini-btn" data-export="csv">CSV</button></div></div><div class="setting-card"><div class="copy"><strong>Импорт JSON</strong><span>Существующие записи не удаляются</span></div><button class="mini-btn" data-import>Выбрать файл</button></div><div class="setting-card danger-zone"><div class="copy"><strong>Удалить все данные</strong><span>Действие необратимо, сначала сделай экспорт</span></div><button class="btn danger" data-clear>Удалить</button></div><p class="notice">ShiftPulse хранит данные локально на этом устройстве. Сервер для работы журнала не нужен. После установки PWA приложение работает офлайн.</p></div>`;$("#goalInput").addEventListener("change",()=>{state.settings.goal=Math.max(0,Number($("#goalInput").value)||0);saveSettings();render()});$("#weekStart").addEventListener("change",()=>{state.settings.weekStart=Number($("#weekStart").value);saveSettings()})}
function toast(t){const el=$("#toast");el.textContent=t;el.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove("show"),2200)}
function modal(title,text,ok,action){$("#modalRoot").innerHTML=`<div class="modal-backdrop" id="modal"><div class="modal"><h3>${title}</h3><p>${text}</p><div class="modal-actions"><button class="btn secondary" data-modal-cancel>Отмена</button><button class="btn ${action==="delete"?"danger":""}" data-modal-ok>${ok}</button></div></div></div>`;$("#modal").addEventListener("click",e=>{if(e.target.id==="modal"||e.target.closest("[data-modal-cancel]"))$("#modalRoot").innerHTML="";if(e.target.closest("[data-modal-ok]")){action==="delete"&&confirmDelete(window.__modalId);if(action==="deleteAll"){dbClear().then(()=>{state.shifts=[];toast("Все данные удалены");render()})}$("#modalRoot").innerHTML=""}})}
async function confirmDelete(id){await dbDelete(id);state.shifts=await dbAll();toast("Смена удалена");render()}
function exportJSON(){const blob=new Blob([JSON.stringify({app:"ShiftPulse",version:1,exportedAt:new Date().toISOString(),settings:state.settings,shifts:state.shifts},null,2)],{type:"application/json"});download(blob,`shiftpulse_${dateISO(new Date())}.json`)}
function exportCSV(){const rows=[["Дата","Начало","Конец","Перерыв","Рабочие часы","Комментарий"],...completed().sort((a,b)=>a.date.localeCompare(b.date)).map(s=>[s.date,s.startTime,s.endTime,minsToClock(s.breakMinutes),minsToHM(s.durationMinutes),s.comment||""])];const csv="\uFEFF"+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n");download(new Blob([csv],{type:"text/csv;charset=utf-8"}),`shiftpulse_${dateISO(new Date())}.csv`)}
function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importJSON(){const input=document.createElement("input");input.type="file";input.accept=".json,application/json";input.onchange=async()=>{try{const data=JSON.parse(await input.files[0].text());const incoming=Array.isArray(data)?data:data.shifts;if(!Array.isArray(incoming))throw Error();for(const s of incoming){if(!s.id)s.id=uid();if(!s.createdAt)s.createdAt=Date.now();await dbPut(s)}if(data.settings)state.settings={...state.settings,...data.settings};saveSettings();state.shifts=await dbAll();toast(`Импортировано: ${incoming.length}`);render()}catch{toast("Не удалось импортировать JSON")}};input.click()}
document.addEventListener("click",async e=>{const nav=e.target.closest("[data-nav]");if(nav){state.view=nav.dataset.nav;state.editId=null;render();return}if(e.target.closest("[data-action='settings']")){state.view="settings";render();return}if(e.target.closest("[data-action='start']")){await startShift();return}if(e.target.closest("[data-action='finish']")){await finishShift();return}const ed=e.target.closest("[data-edit]");if(ed){state.editId=ed.dataset.edit;state.view="add";render();return}const del=e.target.closest("[data-delete]");if(del){window.__modalId=del.dataset.delete;modal("Удалить эту смену?","Запись будет удалена из локальной базы данных.","Удалить","delete");return}const f=e.target.closest("[data-filter]");if(f){state.historyFilter=f.dataset.filter;render();return}const st=e.target.closest("[data-stats]");if(st){state.statsMode=st.dataset.stats;render();return}const cal=e.target.closest("[data-cal]");if(cal){state.calendarDate.setMonth(state.calendarDate.getMonth()+Number(cal.dataset.cal));render();return}const cd=e.target.closest("[data-calday]");if(cd){const found=state.shifts.find(s=>s.date===cd.dataset.calday&&s.status==="completed");if(found){state.editId=found.id;state.view="add";render()}else toast("Смены нет");return}const ex=e.target.closest("[data-export]");if(ex){ex.dataset.export==="json"?exportJSON():exportCSV();return}if(e.target.closest("[data-import]")){importJSON();return}if(e.target.closest("[data-clear]")){window.__modalId="__all";modal("Удалить все данные?","История смен будет удалена с этого устройства. Рекомендуется сначала сделать экспорт.","Удалить всё","deleteAll");return}const ok=e.target.closest("[data-modal-ok]");if(ok&&window.__modalId==="__all"){await dbClear();state.shifts=[];$("#modalRoot").innerHTML="";toast("Все данные удалены");render()}});
async function boot(){loadSettings();state.shifts=await dbAll();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});render();window.addEventListener("resize",()=>{if(state.view==="stats")drawChart(statsRangeData())})}
function statsRangeData(){return []}
boot();